# Generated by Django 5.2.7 on 2025-10-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=18)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.IntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
